### ISSUE TITLE
RuntimeError: mat1 and mat2 shapes cannot be multiplied (123x18 and 19x56)

### ISSUE THREAD

**Issue by zhengyangkust** [luwei0917/TankBind#10]
Hi Wei,

I ran the example prediction code and get error when using the 'affinity_pred_list = torch.cat(affinity_pred_list)', I don't know what caused error and how to fix it. 

Thanks!

![1657422948598](https://user-images.githubusercontent.com/109010112/178129891-f19c4ba8-3b0a-463b-958b-dcf1e9805d2b.jpg)

**Comment by luwei0917** [comment]
please use torchdrug v0.1.2
