### ISSUE TITLE
How to segment the protein with functional blocks?

### ISSUE THREAD

**Issue by Gloria-LIU** [luwei0917/TankBind#12]
Hi, 
Thank you for the amazing work!
I am curious about how to segment the protein and how to choose the native block for a protein-ligand pair.

1. As mentioned in Sec 3.4, "We, therefore, take full use of information stored in the whole protein instead of only the native binding region. " How to ensure the blocks (constructed with p2rank centers) cover the whole protein?

2. As mentioned in Appendix J., "A protein block encloses the ligand when it covers more than 90% of the native interaction." And since a functional block can cover about 200 amino acids. I think the functional blocks would be constructed with some overlaps, right? And thus, there would be multiple blocks that satisfy the above-mentioned condition. Curious about how you deal with such a situation. 

Thank you so much!

**Comment by luwei0917** [comment]
1. We didn't ensure the blocks cover the whole protein, but p2rank typically output all potential binding pockets. The "whole protein" basically means "other than the native binding site, we also consider all other potential binding sites"
2. Yes, a block will be treated as the "native block" as long as it cover more than 90% of the native interaction. A protein could have multiple native blocks.

**Comment by Gloria-LIU** [comment]
Thank you for the quick response. 
I still wonder how you choose the cutoff value of 20A. Do you have any ablation study on this cutoff value?

**Comment by luwei0917** [comment]
we tried a radius of 15A instead of 20Å, no significant difference is found. We didn't explore a lot in this.

**Comment by Gloria-LIU** [comment]
Got it! Thank you so much for answering!
