### ISSUE TITLE
Is the ligand RMSD computed without hydrogen

### ISSUE THREAD

**Issue by KruskalLin** [luwei0917/TankBind#15]
Thanks for your promising contribution! I have a small question when reading the code. I found out that when using `read_mol` method, you remove the hydrogen atom and `mol` object is used for the later process. Is the ligand RMSD also computed based on these conformers (without hydrogen) while training?

Looking forward to your reply!

Sincerely,
Lin

**Comment by luwei0917** [comment]
yes. RMSD is always computed over heavy atoms (no hydrogen).

**Comment by KruskalLin** [comment]
Thank you!

**Comment by KruskalLin** [comment]
Sorry for another small question. Is TankBind trained without hydrogens? I see the codes you remove hydrogen when reading molecules.

Thank you so much!!!

**Comment by luwei0917** [comment]
yes. hydrogens is removed.
