### ISSUE TITLE
RuntimeError: mat1 and mat2 shapes cannot be multiplied (123x18 and 19x56)

### ISSUE THREAD

**Issue by jiaxin-ustc** [luwei0917/TankBind#4]
When i follow the README file and run “high_throughput_virtual_screening_LRRK2_WDR.ipynb” and "prediction_example_using_PDB_6hd6.ipynb” file ，i got the erro info as follow:

RuntimeError                              Traceback (most recent call last)
File ~/anaconda3/envs/tankbind_py38/lib/python3.8/site-packages/torch/nn/modules/module.py:1110, in Module._call_impl(self, *input, **kwargs)
   1106 # If we don't have any hooks, we want to skip the rest of the logic in
   1107 # this function, and just call forward.
   1108 if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1109         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1110     return forward_call(*input, **kwargs)
   1111 # Do not call functions when jit is used
   1112 full_backward_hooks, non_full_backward_hooks = [], []

File ~/TankBind-main-new/TankBind-main/examples/../tankbind/model.py:343, in IaBNet_with_affinity.forward(self, data)
    341     edge_weight = data[("compound", "c2c", "compound")].edge_weight
    342     compound_batch = data['compound'].batch
--> 343     compound_out = self.conv_compound(compound_edge_index,edge_weight,compound_edge_feature,compound_x.shape[0],compound_x)['node_feature']
    345 # protein_batch version could further process b matrix. better than for loop.
    346 # protein_out_batched of shape b, n, c
...
File ~/anaconda3/envs/tankbind_py38/lib/python3.8/site-packages/torch/nn/modules/linear.py:103, in Linear.forward(self, input)
    102 def forward(self, input: Tensor) -> Tensor:
--> 103     return F.linear(input, self.weight, self.bias)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (123x18 and 19x56)

it seems like the example data given not match GVP size, i'd appreciate it If you could help me fix it.

**Comment by luwei0917** [comment]
Please use torchdrug v0.1.2 
There is a compatibility issue with the v0.1.3

**Comment by jiaxin-ustc** [comment]
thank you so much, this solution indeed fix it.
