### ISSUE TITLE
split_protein_and_ligand

### ISSUE THREAD

**Issue by ileump** [luwei0917/TankBind#9]
Hi Wei,

I ran the example prediction code and get error when using the 'split_protein_and_ligand', i wonder if it's a network problem from jupyter lab or other problem. 

Thanks!

<img width="2161" alt="Xnip2022-07-01_15-49-48" src="https://user-images.githubusercontent.com/87130950/176852153-9802e9b5-3f8c-4dd9-a5df-0fe8fe7865c8.png">

**Comment by luwei0917** [comment]
yes. it seems a network problem. The code tries to download the sdf file but failed.
you probably have to prepare the .pdb, and .sdf file yourself.

**Comment by ileump** [comment]
hello, another question about the supported protein structure, does tankbind currently support the protein structure predicted by AlphaFold?

**Comment by luwei0917** [comment]
kind of. I think the result won't be very bad. but, we haven't test its performance with AlphaFold structure.
